Traceback (most recent call last):
  File "python_for_loops.py", line 41, in <module>
    y
NameError: name 'y' is not defined
srun: error: compute-3-4: task 0: Exited with exit code 1
